# Включает поддержку конструкции import.meta.url
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] # разрешает подчёркивание в именах только для двух констант
env:
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
# parserOptions:
#   ecmaVersion: 2018
#   sourceType: module
# rules: {}
